services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cfp_user
      POSTGRES_PASSWORD: cfp_pass
      POSTGRES_DB: cfp_db
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  localstack:
    image: localstack/localstack:3.8.1
    ports: ["4566:4566"]
    environment:
      SERVICES: s3,sqs
    volumes:
      - localstackdata:/var/lib/localstack
      - ./docker/localstack/init.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  pgdata:
  localstackdata:
