apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: cfp
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: cloud-backend:latest
          imagePullPolicy: IfNotPresent
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef: { name: app-secrets, key: DATABASE_URL }